/** Фактические характеристики для сравнительных статей (ориентир 2026, без привязки к рекламе брендов). */

export const ZOOMER = {
  shortName: 'Зумерский VPN',
  protocol: 'VLESS Reality (Xray)',
  price: 'от 99 ₽ / 7 дней; год от 2399 ₽',
  freeTier: 'Пробный период на главной, без карты',
  platforms: 'iOS, Android, Windows, macOS — Happ / V2rayTun',
  servers: 'Германия, NL, Польша, США',
  speed: 'Каналы до 10 Гбит/с; акцент на стабильный стриминг',
  devices: 'До 5 одновременно',
  setup: 'Telegram-бот → личный кабинет → импорт subscription',
  logs: 'З заявленной политикой no-logs',
  payment: 'СБП, карты РФ, криптовалюта',
  support: 'Telegram, русский язык',
  bestFor: 'Быстрый старт без VPS, оплата в рублях, домашний и мобильный интернет',
  weakFor: 'Нужен свой сервер или open-source только на своём VPS',
};

/** @typedef {typeof VPN_FACTS.amnezia} VpnFact */
export const VPN_FACTS = {
  amnezia: {
    slug: 'amnezia-vpn',
    name: 'Amnezia VPN',
    type: 'self-hosted',
    protocol: 'AmneziaWG, OpenVPN, Shadowsocks, Cloak (на вашем VPS)',
    price: 'Приложение бесплатно; платите только за VPS (от ~300–500 ₽/мес)',
    freeTier: 'Нет облачных серверов — «бесплатно» только если VPS уже есть',
    platforms: 'Windows, macOS, Linux, Android, iOS',
    servers: 'Любой ваш VPS (Hetzner, AEZA и т.д.)',
    speed: 'Зависит от VPS и маршрута; часто высокая при хорошем хосте',
    devices: 'По лимитам вашего сервера/конфига',
    setup: 'Нужно арендовать VPS, установить Amnezia, сгенерировать ключи',
    logs: 'Контроль у вас на VPS; провайдер VPS видит IP сервера',
    payment: 'Оплата VPS отдельно, часто карты/крипто зарубежных хостеров',
    support: 'Сообщество, GitHub; коммерческой линии «как у VPN-сервиса» нет',
    pros: [
      'Полный контроль над сервером и протоколом',
      'Open source, прозрачная логика',
      'Можно подобрать локацию VPS под задачу',
    ],
    cons: [
      'Не «включил и смотри YouTube» — нужна настройка VPS',
      'При недоступности IP VPS придётся менять инфраструктуру',
      'Нет готовой поддержки «не подключается — помогите»',
    ],
    bestFor: 'Техничным пользователям с VPS, кому важен self-host',
    weakFor: 'Новичкам, кому нужен готовый VPN за 2 минуты из Telegram',
    speedNote: 'На мощном EU VPS часто 100+ Мбит/с; на слабом — просадки',
    reviewNote: 'Хвалят за приватность и гибкость; ругают за порог входа',
  },
  adguard: {
    slug: 'adguard-vpn',
    name: 'AdGuard VPN',
    type: 'commercial',
    protocol: 'Собственный протокол AdGuard + WireGuard на части платформ',
    price: 'Подписка ~€3–5/мес или годовой план (зависит от акций)',
    freeTier: 'Ограниченный бесплатный режим с лимитом трафика/скорости',
    platforms: 'Windows, macOS, Android, iOS, расширения браузера',
    servers: 'Десятки стран, коммерческая сеть AdGuard',
    speed: 'Стабильна на близких серверах; free tier режется',
    devices: 'По тарифу, несколько устройств на подписке',
    setup: 'Установка из store, аккаунт AdGuard, вход в подписку',
    logs: 'Политика AdGuard; не self-hosted',
    payment: 'Карты, PayPal; для РФ оплата может быть неудобна',
    support: 'Тикеты AdGuard, английский/русский в документации',
    pros: [
      'Удобные приложения и связка с AdGuard DNS/блокировщиком',
      'Понятный интерфейс для новичков',
      'WireGuard на части клиентов',
    ],
    cons: [
      'Не VLESS Reality — другая модель работы в нестабильных сетях',
      'Оплата из РФ периодически осложняется',
      'Free tier не для ежедневного 4K-YouTube',
    ],
    bestFor: 'Пользователям экосистемы AdGuard, браузерный VPN + приложения',
    weakFor: 'Кому нужен оплата СБП и Reality для нестабильных сетей',
    speedNote: 'На EU часто 50–150 Мбит/с; free — ниже',
    reviewNote: 'Отзывы: «просто и чисто»; минусы — цена и лимиты free',
  },
  proton: {
    slug: 'proton-vpn',
    name: 'Proton VPN',
    type: 'commercial',
    protocol: 'WireGuard, OpenVPN, Stealth (Proton)',
    price: 'Free + Plus от ~€4–10/мес (зависит от плана)',
    freeTier: 'Free: ограниченные страны, 1 устройство, средняя скорость',
    platforms: 'Все основные ОС, Linux, роутеры на Plus',
    servers: 'Широкая сеть, Secure Core на платных планах',
    speed: 'Plus — высокая; Free — очереди и throttling в пик',
    devices: 'Free: 1; Plus: 10',
    setup: 'Аккаунт Proton, приложение из store',
    logs: 'Швейцарская юрисдикция, audited no-logs заявление',
    payment: 'Карта, PayPal; рублёвая оплата не основной сценарий',
    support: 'Поддержка Proton, в основном EN',
    pros: [
      'Сильная репутация приватности и аудиты',
      'Free тариф для базовых задач',
      'Stealth для сложных сетей (Plus)',
    ],
    cons: [
      'Free не подходит для ежедневной работы и длинных сессий',
      'Plus дороже локальных сервисов в рублях',
      'Нет VLESS Reality и привычного RU-бота выдачи ключей',
    ],
    bestFor: 'Privacy-ориентированным с оплатой зарубежной картой',
    weakFor: 'Бюджетный ежедневный стриминг без Plus',
    speedNote: 'Plus EU: часто 100+ Мбит/с; Free — нестабильно вечером',
    reviewNote: 'Trustpilot: хвалят privacy; free ругают за скорость',
  },
  windscribe: {
    slug: 'windscribe',
    name: 'Windscribe',
    type: 'commercial',
    protocol: 'WireGuard, OpenVPN, IKEv2, Stealth/WStunnel',
    price: 'Free 10 ГБ/мес + Pro ~$9/мес или Build-a-plan',
    freeTier: '10 ГБ/мес, ограниченный список локаций',
    platforms: 'Desktop, mobile, расширения, Fire TV',
    servers: '60+ стран, R.O.B.E.R.T. фильтры',
    speed: 'Pro хорош на ближайших узлах; free — лимит трафика',
    devices: 'Unlimited на Pro',
    setup: 'Аккаунт, клиент, логин',
    logs: 'No-logs заявление, Канада',
    payment: 'Карты; оплата из РФ — через посредников',
    support: 'Тикеты, wiki, EN',
    pros: [
      'Гибкий Build-a-plan',
      'Stealth для нестабильных сетей',
      'Расширение для браузера',
    ],
    cons: [
      '10 ГБ быстро кончаются на видео',
      'Не все протоколы одинаково устойчивы в РФ',
      'Нет русскоязычной «быстрой» поддержки как в TG-боте',
    ],
    bestFor: 'Умеренный трафик, браузер + иногда mobile',
    weakFor: 'Ежедневный YouTube 4K и большие загрузки на free',
    speedNote: 'Pro: 50–200 Мбит/с на EU; free упирается в cap',
    reviewNote: 'Любят цену Pro; free — «хватило на неделю»',
  },
  outline: {
    slug: 'outline-vpn',
    name: 'Outline VPN',
    type: 'self-hosted',
    protocol: 'Shadowsocks (Outline)',
    price: 'Клиент бесплатен; сервер — ваш VPS или Outline Manager',
    freeTier: 'Нет готовой сети — только свой ключ',
    platforms: 'Windows, macOS, Linux, Android, iOS, ChromeOS',
    servers: 'Тот VPS, который настроили (DigitalOcean и др.)',
    speed: 'Как у VPS; Shadowsocks лёгкий',
    devices: 'Много ключей через Manager',
    setup: 'Outline Manager на VPS, раздача access keys',
    logs: 'Зависит от хостера VPS',
    payment: 'VPS отдельно',
    support: 'Jigsaw/Outline docs; community',
    pros: [
      'Простой Shadowsocks для команды/семьи',
      'Прозрачная модель «свой сервер»',
      'Лёгкий клиент',
    ],
    cons: [
      'Shadowsocks чаще работает нестабильно, чем Reality',
      'Нужен VPS и админка',
      'Нет готовых DE/NL/US «из коробки»',
    ],
    bestFor: 'Малые команды с одним VPS',
    weakFor: 'Пользователи без желания администрировать',
    speedNote: 'На хорошем VPS — высокая; в нестабильных сетях возможны обрывы',
    reviewNote: 'Хвалят простоту; жалуются на нестабильность SS',
  },
  planet: {
    slug: 'planet-vpn',
    name: 'Planet VPN',
    type: 'commercial-freemium',
    protocol: 'Закрытый стек (типично OpenVPN/ IKE на mobile)',
    price: 'Freemium + Premium подписка в приложении',
    freeTier: 'Бесплатные серверы с рекламой/лимитами (зависит от версии)',
    platforms: 'В основном Android, iOS; desktop ограниченно',
    servers: 'Несколько бесплатных локаций + premium',
    speed: 'Free — переменная; premium лучше, но не топ tier',
    devices: 'По аккаунту приложения',
    setup: 'Установка из store, часто без сложного конфига',
    logs: 'Политика оператора приложения',
    payment: 'In-app Google/Apple',
    support: 'Email/форма в приложении',
    pros: [
      'Быстрый старт на телефоне',
      'Подходит «попробовать VPN»',
      'Не нужен VPS',
    ],
    cons: [
      'Мало прозрачности по протоколам',
      'Free с ограничениями и нестабильностью',
      'Слабее для desktop и power users',
    ],
    bestFor: 'Мобильный casual-доступ',
    weakFor: 'Стабильный desktop, Telegram-звонки, 4K',
    speedNote: 'Free часто 5–30 Мбит/с; premium выше, но не гарантировано',
    reviewNote: 'Смешанные отзывы: удобно vs «перестало работать»',
  },
  psiphon: {
    slug: 'psiphon',
    name: 'Psiphon',
    type: 'circumvention',
    protocol: 'Psiphon (VPN mode), SSH, HTTP proxy — не классический VPN',
    price: 'Бесплатно; Psiphon Pro — donation/подписка в части регионов',
    freeTier: 'Основной режим бесплатный с ограничением скорости',
    platforms: 'Android, iOS, Windows',
    servers: 'Динамическая сеть Psiphon',
    speed: 'Низкая–средняя; не для 4K',
    devices: 'Обычно одно приложение',
    setup: 'Установить и включить — без ключей',
    logs: 'Политика Psiphon; задача — доступ, не anonymity marketing',
    payment: 'Donation/Pro где доступно',
    support: 'FAQ Psiphon',
    pros: [
      'Бесплатный доступ «здесь и сейчас»',
      'Не нужна регистрация для базового режима',
      'Работает как сервис разового доступа, а не как premium VPN',
    ],
    cons: [
      'Не для стриминга и игр',
      'Скорость и стабильность скачут',
      'Не VLESS/Reality и не замена полноценному VPN-сервису',
    ],
    bestFor: 'Разовый тест сервиса без регистрации',
    weakFor: 'Стриминг, звонки, ежедневная работа',
    speedNote: 'Часто 1–10 Мбит/с в пик; latency высокий',
    reviewNote: '«Спас в поездке» vs «слишком медленно»',
  },
};

export const COMPETITOR_KEYS = Object.keys(VPN_FACTS);
